version: "3.9"

services:
  ssh-gateway:
    build:
      context: ../..
      dockerfile: ./modules/ssh-gateway/Dockerfile
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/ssh-gateway:${SEPAL_VERSION:-latest}"
    container_name: ssh-gateway
    volumes:
      - "${SEPAL_DATA_DIR}/ssh-gateway:/data"
      - "${SEPAL_DATA_DIR}/ldap/certificates/ldap-ca.crt.pem:/etc/ldap/certificates/ldap-ca.crt.pem"
      - "${SEPAL_DATA_DIR}/user/home:/home" # Users home directories with ssh keys
    ports:
      - "${SEPAL_SSH_IP:-0.0.0.0}:${SEPAL_SSH_PORT_1:-22}:22"
      - "${SEPAL_SSH_IP:-0.0.0.0}:${SEPAL_SSH_PORT_2:-443}:22"
    extra_hosts:
      - "syslog_host: ${SEPAL_IP:-127.0.0.1}"
    environment:
      SEPAL_HOST: "${SEPAL_HOST}"
      SEPAL_ADMIN_PASSWORD: "${SEPAL_ADMIN_PASSWORD}"
      LDAP_HOST: "${LDAP_HOST}"
      LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWORD}"
    networks:
      - sepal
    restart: always

networks:
  sepal:
    external: true
    name: sepal
