services:
  ssh-gateway:
    volumes:  # To allow dynamic reloading in dev
      - ${SEPAL_PROJECT_DIR}/lib/js/shared:/usr/local/src/sepal/lib/js/shared
      - ${SEPAL_PROJECT_DIR}/modules/ssh-gateway:/usr/local/src/sepal/modules/ssh-gateway
    extra_hosts:
      - 'host.docker.internal:host-gateway'