version: "3.9"

services:
  ceo-gateway:
    build:
      context: ../..
      dockerfile: ./modules/ceo-gateway/Dockerfile
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/ceo-gateway:${SEPAL_VERSION:-latest}"
    container_name: ceo-gateway
    init: true
    volumes:
      - "${SEPAL_DATA_DIR}:/data"
      - "${SEPAL_BACKUP_DIR}:/ceo-gateway"
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
      CEO_URL: "${CEO_URL}"
      CEO_USERNAME: "${CEO_USERNAME}"
      CEO_PASSWORD: "${CEO_PASSWORD}"
      CEO_INSTITUTION_ID: "${CEO_INSTITUTION_ID}"
      CEO_USER_ID: "${CEO_USER_ID}"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - sepal

networks:
  sepal:
    external: true
    name: sepal
