version: "3.9"

services:
  terminal:
    build:
      context: ../..
      dockerfile: ./modules/terminal/Dockerfile
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/terminal:${SEPAL_VERSION:-latest}"
    container_name: terminal
    init: true
    volumes:
      - "${SEPAL_DATA_DIR}/user/home:/sepalUsers" # Users home directories with ssh keys
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
      SSH_GATEWAY_HOST: 'ssh-gateway'
    networks:
      - sepal

networks:
  sepal:
    external: true
    name: sepal
