version: "3.9"

services:
  terminal:
    build:
      context: ../..
      dockerfile: ./modules/terminal/Dockerfile
    image: "${SEPAL_DOCKER_REPOSITORY:-localhost}/openforis/terminal:${SEPAL_VERSION:-latest}"
    container_name: terminal
    volumes:
      - "${SEPAL_DATA_DIR}/user/home:/sepalUsers" # Users home directories with ssh keys
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
      SSH_GATEWAY_HOST: 'ssh-gateway'
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - sepal

networks:
  sepal:
    name: sepal
