services:
  geospatial-toolkit:
    build:
      context: ../..
      dockerfile: ./modules/sandbox/Dockerfile
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/sandbox:${SEPAL_VERSION:-latest}"
    container_name: sandbox
    networks:
      - sepal
    platform: linux/amd64 # Required for macOS builds

networks:
  sepal:
    external: true
