version: "3.9"

services:
  user-storage-backup:
    build:
      context: ../..
      dockerfile: ./modules/user-storage-backup/Dockerfile
    image: "${SEPAL_DOCKER_REPOSITORY:-localhost}/openforis/user-storage-backup:${SEPAL_VERSION:-latest}"
    container_name: user-storage-backup
    volumes:
      - "${SEPAL_DATA_DIR}:/data"
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      S3_BACKUP_BUCKET: "${S3_BACKUP_BUCKET}"
      BACKUP_CRON_EXP: "0 2 * * *"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - sepal

networks:
  sepal:
    external: true
    name: sepal
