version: "3.9"

services:
  user-storage-backup:
    build:
      context: ../..
      dockerfile: ./modules/user-storage-backup/Dockerfile
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/user-storage-backup:${SEPAL_VERSION:-latest}"
    container_name: user-storage-backup
    volumes:
      - "${SEPAL_DATA_DIR}:/data"
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      S3_BACKUP_BUCKET: "${S3_BACKUP_BUCKET}"
      BACKUP_CRON_EXP: "0 2 * * *"
    networks:
      - sepal
    restart: always

networks:
  sepal:
    external: true
    name: sepal
