version: "3.9"

services:
  sepal:
    ports:
      - "127.0.0.1:5005:5005"
    volumes:
      - "${SEPAL_PROJECT_DIR}/common/src:/usr/local/src/sepal/common/src"
      - "${SEPAL_PROJECT_DIR}/common/build:/usr/local/src/sepal/common/build"
      - "${SEPAL_PROJECT_DIR}/modules/sepal-server/src:/usr/local/src/sepal/modules/sepal-server/src"
      - "${SEPAL_PROJECT_DIR}/modules/sepal-server/build:/usr/local/src/sepal/modules/sepal-server/build"
    environment:
      SEPAL_HOST_PROJECT_DIR: "${SEPAL_PROJECT_DIR}"

  socat:
    image: alpine/socat
    container_name: docker-api
    command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:2375:2375"
    networks:
      - sepal
