version: "3.9"

services:
  sepal:
    ports:
      - "0.0.0.0:5005:5005"
    volumes:
      - "${SEPAL_PROJECT_DIR}/modules/sepal-server/src:/usr/local/src/sepal/modules/sepal-server/src"
      - "${SEPAL_PROJECT_DIR}/modules/sepal-server/build:/usr/local/src/sepal/modules/sepal-server/build"
  socat:
    image: bobrik/socat
    container_name: docker-api
    command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "2375:2375"
    networks:
      - sepal
