version: "3.9"

services:
  kafka:
    build:
      dockerfile: Dockerfile
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/kafka:${SEPAL_VERSION:-latest}"
    container_name: kafka
    volumes:
      - "${SEPAL_DATA_DIR}/kafka:/var/lib/kafka"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    networks:
      - sepal
    restart: unless-stopped
    healthcheck:
      test: netstat -nl | grep -e ':9092\s'
      timeout: 60s
      interval: 1s
      retries: 60

networks:
  sepal:
    external: true
    name: sepal
