jenkins:
  numExecutors: 1
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "jenkins"
          password: "${JENKINS_PASSWORD}"
  authorizationStrategy: loggedInUsersCanDoAnything
  mode: NORMAL

unclassified:
  location:
    url: https://${JENKINS_DOMAIN}:${JENKINS_PORT}/
