services:
  jenkins:
    build:
      context: .
    image: jenkins
    container_name: jenkins
    environment:
      CASC_JENKINS_CONFIG: /var/lib/jenkins/casc
      JENKINS_PASSWORD: "${JENKINS_PASSWORD}"
      DOCKER_REGISTRY_USERNAME: "${DOCKER_REGISTRY_USERNAME}"
      DOCKER_REGISTRY_PASSWORD: "${DOCKER_REGISTRY_PASSWORD}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - home:/var/jenkins_home
    restart: always
    ulimits:
      core: 0
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/8080"
      timeout: 60s
      interval: 1s
      retries: 60

  haproxy:
    extends:
      file: ../haproxy-acme/docker-compose.yml
      service: haproxy-acme
    depends_on:
      jenkins:
        condition: service_healthy
    ports:
      - "8443:8443"
    volumes:
      - "${SEPAL_PROJECT_DIR}/modules/jenkins/haproxy.cfg:/etc/haproxy/haproxy.d/jenkins.cfg"
      - haproxy:/var/lib/acme

volumes:
  haproxy:
  home:
