services:
  jenkins:
    build:
      context: .
    image: jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
    environment:
      CASC_JENKINS_CONFIG: /var/lib/jenkins/casc
      JENKINS_PASSWORD: "${JENKINS_PASSWORD}"
      DOCKER_REGISTRY_USERNAME: "${DOCKER_REGISTRY_USERNAME}"
      DOCKER_REGISTRY_PASSWORD: "${DOCKER_REGISTRY_PASSWORD}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - home:/var/jenkins_home
    restart: always
    ulimits:
      core: 0

volumes:
  home: