- name: Build and push images
  hosts: all
  user: ec2-user
  become: yes
  gather_facts: true

  vars_files:
    - "{{ secret_vars_file }}"

  roles:
    - { role: build-module, module: email }
    - { role: build-module, module: sys-monitor }
    - { role: build-module, module: letsencrypt }
    - { role: build-module, module: java }
    - { role: build-module, module: rabbitmq }
    - { role: build-module, module: ldap-backup }
    - { role: build-module, module: ldap }
    - { role: build-module, module: haproxy }
    - { role: build-module, module: backup }
    - { role: build-module, module: mysql-backup }
    - { role: build-module, module: mysql }
    - { role: build-module, module: gateway }
    - { role: build-module, module: terminal }
    - { role: build-module, module: ssh-gateway }
    - { role: build-module, module: geospatial-toolkit }
    - { role: build-module, module: sandbox }
    - { role: build-module, module: task }
    - { role: build-module, module: gee }
    - { role: build-module, module: user }
    - { role: build-module, module: user-storage }
    - { role: build-module, module: user-storage-backup }
    - { role: build-module, module: user-files }
    - { role: build-module, module: gui }
    - { role: build-module, module: ceo-gateway }
    - { role: build-module, module: app-manager }
    - { role: build-module, module: sepal-server }
    - role: push-images
