version: "3.9"

services:
  user:
    ports:
      - "127.0.0.1:5006:5005"
    volumes:
      - "./src:/usr/local/src/sepal/modules/user/src"
      - "./build:/usr/local/src/sepal/modules/user/build"
