version: "3.9"

services:
  gateway-redis:
    image: "redis:6"
    container_name: gateway-redis
    volumes:
      - "${SEPAL_DATA_DIR}/gateway-redis:/data"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - sepal

  gateway:
    build:
      context: ../..
      dockerfile: ./modules/gateway/Dockerfile
    image: "${SEPAL_DOCKER_REPOSITORY:-localhost}/openforis/gateway:${SEPAL_VERSION:-latest}"
    container_name: gateway
    init: true
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
      SEPAL_HOST: "${SEPAL_HOST}"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - sepal
    ulimits:
      nproc: 65535
      nofile:
        soft: 65536
        hard: 65536
    sysctls:
      net.ipv4.tcp_keepalive_time: 60
      net.ipv4.tcp_keepalive_intvl: 60
      net.ipv4.tcp_keepalive_probes: 6

networks:
  sepal:
    name: sepal
