version: "3.9"

services:
  gateway:
    volumes:  # To allow dynamic reloading in dev
      - ${SEPAL_PROJECT_DIR}/lib/js/shared/src:/usr/local/src/sepal/lib/js/shared/src
      - ${SEPAL_PROJECT_DIR}/modules/gateway/src:/usr/local/src/sepal/modules/gateway/src
