services:
  haproxy:
    extends:
      file: ../docker-compose.logger.override.yml
      service: logger
    volumes:  # To allow dynamic reloading in dev
      - ${SEPAL_PROJECT_DIR}/modules/haproxy/config:/config
