services:
  haproxy:
    build:
      context: ../..
      dockerfile: ./modules/haproxy/Dockerfile
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/haproxy:${SEPAL_VERSION:-latest}"
    container_name: haproxy
    ports:
      - "${SEPAL_IP:-0.0.0.0}:${SEPAL_HTTP_PORT:-80}:80"
      - "${SEPAL_IP:-0.0.0.0}:${SEPAL_HTTPS_PORT:-443}:443"
    volumes:
      - "${SEPAL_DATA_DIR}/letsencrypt:/etc/letsencrypt"
    environment:
      SEPAL_HOST: "${SEPAL_HOST}"
    networks:
      - sepal
    ulimits:
      nproc: 65535
      nofile:
        soft: 65536
        hard: 65536
    sysctls:
      net.ipv4.tcp_keepalive_time: 60
      net.ipv4.tcp_keepalive_intvl: 60
      net.ipv4.tcp_keepalive_probes: 6
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/80"
      timeout: 60s
      interval: 1s
      retries: 60
    restart: always

networks:
  sepal:
    external: true
    name: sepal
