version: "3.9"

services:
  task:
    build:
      context: ../..
      dockerfile: ./modules/task/Dockerfile
    image: "${SEPAL_DOCKER_REPOSITORY:-localhost}/openforis/task:${SEPAL_VERSION:-latest}"
    container_name: task
    init: true
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
      SEPAL_HOST: "${SEPAL_HOST}"
      SEPAL_ENDPOINT: "${SEPAL_ENDPOINT}"
      SEPAL_ADMIN_PASSWORD: "${SEPAL_ADMIN_PASSWORD}"
      EE_ACCOUNT: "${EE_ACCOUNT}"
      EE_PRIVATE_KEY: "${EE_PRIVATE_KEY}"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - sepal

networks:
  sepal:
    external: true
    name: sepal
