version: "3.9"

services:
  task:
    build:
      context: ../..
      dockerfile: ./modules/task/Dockerfile
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/task:${SEPAL_VERSION:-latest}"
    container_name: task
    init: true
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
      SEPAL_HOST: "${SEPAL_HOST}"
      SEPAL_ENDPOINT: "${SEPAL_ENDPOINT}"
      SEPAL_ADMIN_PASSWORD: "${SEPAL_ADMIN_PASSWORD}"
      EE_ACCOUNT: "${EE_ACCOUNT}"
      EE_PRIVATE_KEY: "${EE_PRIVATE_KEY}"
    networks:
      - sepal
    ulimits:
      core: 0
    platform: linux/amd64 # Required for macOS builds

networks:
  sepal:
    external: true
    name: sepal
