services:
  r-proxy-redis:
    image: "redis:6"
    container_name: r-proxy-redis
    volumes:
      - "${SEPAL_DATA_DIR}/r-proxy-redis:/data"
    networks:
      - sepal
    restart: always

  r-proxy:
    build:
      context: ../..
      dockerfile: ./modules/r-proxy/Dockerfile
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/r-proxy:${SEPAL_VERSION:-latest}"
    container_name: r-proxy
    init: true
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
    networks:
      - sepal
    ports:
      - "${SEPAL_IP:-0.0.0.0}:8180:8180"
    volumes:
      - ${SEPAL_DATA_DIR}/r-proxy/site-library:/usr/local/lib/R/site-library
      - ${SEPAL_DATA_DIR}/r-proxy/repo:/R
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/8180"
      timeout: 60s
      interval: 1s
      retries: 60
    restart: always
    ulimits:
      core: 0
    platform: linux/amd64 # Required for macOS builds

networks:
  sepal:
    external: true
    name: sepal
