version: "3.9"

services:
  r-proxy-redis:
    image: "redis:6"
    container_name: r-proxy-redis
    volumes:
      - "${SEPAL_DATA_DIR}/r-proxy-redis:/data"
    networks:
      - sepal
    restart: always

  r-proxy:
    build:
      context: ../..
      dockerfile: ./modules/r-proxy/Dockerfile
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/r-proxy:${SEPAL_VERSION:-latest}"
    container_name: r-proxy
    init: true
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
    networks:
      - sepal
    ports:
      - "8180:8180"
    volumes:
      - ${SEPAL_DATA_DIR}/r-proxy/site-library:/usr/local/lib/R/site-library
      - ${SEPAL_DATA_DIR}/r-proxy/repo:/R
    restart: always

networks:
  sepal:
    external: true
    name: sepal
