version: "3.9"

services:
  r-proxy-redis:
    image: "redis:6"
    container_name: r-proxy-redis
    volumes:
      - "${SEPAL_DATA_DIR}/r-proxy-redis:/data"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - sepal

  r-proxy:
    build:
      context: ../..
      dockerfile: ./modules/r-proxy/Dockerfile
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/r-proxy:${SEPAL_VERSION:-latest}"
    container_name: r-proxy
    init: true
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - sepal
    ports:
      - "8180:8180"
    volumes:
      - ${SEPAL_DATA_DIR}/r-proxy/site-library:/usr/local/lib/R/site-library
      - ${SEPAL_DATA_DIR}/r-proxy/repo:/R

  # r-proxy-test:
  #   image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/r:${SEPAL_VERSION:-latest}"
  #   container_name: r-proxy-test
  #   environment:
  #     DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
  #     SEPAL_HOST: "${SEPAL_HOST}"
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #   networks:
  #     - sepal
  #   tty: true

networks:
  sepal:
    external: true
    name: sepal
