version: "3.9"

services:
  mysql:
    build:
      context: ../..
      dockerfile: ./modules/mysql/Dockerfile
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/mysql:${SEPAL_VERSION:-latest}"
    container_name: mysql
    volumes:
      - "${SEPAL_DATA_DIR}/mysql:/data"
      # Parent image volume
      - "${SEPAL_DATA_DIR}/mysql/db:/var/lib/mysql"
    environment:
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - sepal
    healthcheck:
      test: [ "CMD", "test", "-f", "/data/module_initialized" ]
      timeout: 60s
      interval: 1s
      retries: 60
  mysql-admin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: mysql-admin
    restart: always
    environment:
      PMA_HOST: mysql
    ports:
      - "127.0.0.1:8080:80"
    networks:
      - sepal
    depends_on:
      - mysql
networks:
  sepal:
    external: true
    name: sepal
