services:
  mysql:
    extends:
      file: ../docker-compose.logger.override.yml
      service: logger

  mysql-admin:
    extends:
      file: ../docker-compose.logger.override.yml
      service: logger
