version: "3.9"

services:
  geospatial-toolkit:
    build:
      context: ../..
      dockerfile: ./modules/geospatial-toolkit/Dockerfile
      network: sepal
    image: "openforis/geospatial-toolkit:latest"
    container_name: geospatial-toolkit
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - sepal

networks:
  sepal:
    external: true
    name: sepal
