version: "3.9"

services:
  user-files:
    build:
      context: ../..
      dockerfile: ./modules/user-files/Dockerfile
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/user-files:${SEPAL_VERSION:-latest}"
    container_name: user-files
    init: true
    volumes:
      - "${SEPAL_DATA_DIR}/sepal/home:/sepalUsers"
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
      POLL_INTERVAL_MS: "6000"
    networks:
      - sepal

networks:
  sepal:
    external: true
    name: sepal
