version: "3.9"

services:
  user-files:
    build:
      context: ../..
      dockerfile: ./modules/user-files/Dockerfile
    image: "${SEPAL_DOCKER_REPOSITORY:-localhost}/openforis/user-files:${SEPAL_VERSION:-latest}"
    container_name: user-files
    init: true
    volumes:
      - "${SEPAL_DATA_DIR}/sepal/home:/sepalUsers"
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
      POLL_INTERVAL_MS: "6000"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - sepal

networks:
  sepal:
    name: sepal
