version: "3.9"

services:
  rabbitmq:
    build:
      context: ../..
      dockerfile: ./modules/rabbitmq/Dockerfile
    image: "${SEPAL_DOCKER_REPOSITORY:-localhost}/openforis/rabbitmq:${SEPAL_VERSION:-latest}"
    container_name: rabbitmq
    ports:
      - "${SEPAL_IP_ADDRESS:-0.0.0.0}:5672:5672"
      - "127.0.0.1:15672:15672"
    volumes:
      - "${SEPAL_DATA_DIR}/rabbitmq:/var/lib/rabbitmq"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - sepal

networks:
  sepal:
    external: true
    name: sepal
