version: "3.9"

services:
  rabbitmq:
    build:
      context: ../..
      dockerfile: ./modules/rabbitmq/Dockerfile
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/rabbitmq:${SEPAL_VERSION:-latest}"
    container_name: rabbitmq
    ports:
      - "${SEPAL_IP:-0.0.0.0}:5672:5672"
      - "127.0.0.1:15672:15672"
    volumes:
      - "${SEPAL_DATA_DIR}/rabbitmq:/var/lib/rabbitmq"
    networks:
      - sepal
    restart: always      

networks:
  sepal:
    external: true
    name: sepal
