services:
  sys-monitor:
    build:
      context: ../..
      dockerfile: ./modules/sys-monitor/Dockerfile
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/sys-monitor:${SEPAL_VERSION:-latest}"
    container_name: sys-monitor
    init: true
    volumes:
      - "/var/log:/log:ro"
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
      SEPAL_SERVER_LOG: "/log/messages"
      INITIAL_DELAY_MINUTES: "10"
      AUTO_REARM_DELAY_HOURS: "24"
      SEPAL_MONITORING_EMAIL: "${SEPAL_MONITORING_EMAIL}"
    networks:
      - sepal
    restart: always
    ulimits:
      core: 0

networks:
  sepal:
    external: true
    name: sepal
