version: "3.9"

services:
  sys-monitor:
    build:
      context: ../..
      dockerfile: ./modules/sys-monitor/Dockerfile
    image: "${SEPAL_DOCKER_REPOSITORY:-localhost}/openforis/sys-monitor:${SEPAL_VERSION:-latest}"
    container_name: sys-monitor
    init: true
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
      SEPAL_SERVER_LOG: "/log/messages"
      INITIAL_DELAY_MINUTES: "10"
      AUTO_REARM_DELAY_HOURS: "24"
      SEPAL_MONITORING_EMAIL: "${SEPAL_MONITORING_EMAIL}"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - sepal

networks:
  sepal:
    external: true
    name: sepal
