version: "3.9"

services:
  sys-monitor:
    build:
      context: ../..
      dockerfile: ./modules/sys-monitor/Dockerfile
    image: "${SEPAL_DOCKER_REPOSITORY:-localhost}/openforis/sys-monitor:${SEPAL_VERSION:-latest}"
    container_name: sys-monitor
    init: true
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - sepal

networks:
  sepal:
    name: sepal
