version: "3.9"

services:
  r-package-manager:
    build:
      context: ../..
      dockerfile: ./modules/r-package-manager/Dockerfile
    image: "${SEPAL_DOCKER_REPOSITORY:-localhost}/openforis/r-package-manager:${SEPAL_VERSION:-latest}"
    container_name: r-package-manager
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
      POLL_INTERVAL_S: 86400
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - sepal

networks:
  sepal:
    name: sepal
