version: "3.9"

services:
  gui:
    build:
      context: ../..
      dockerfile: ./modules/gui/Dockerfile
      args:
        BUILD_NUMBER: "${BUILD_NUMBER}"
        GIT_COMMIT: "${GIT_COMMIT}"
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/gui:${SEPAL_VERSION:-latest}"
    container_name: gui
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
      GOOGLE_ANALYTICS_ID: "${GOOGLE_ANALYTICS_ID}"
      GOOGLE_MAPS_API_KEY: "${GOOGLE_MAPS_API_KEY}"
      GOOGLE_RECAPTCHA_SITE_KEY: "${GOOGLE_RECAPTCHA_SITE_KEY}"
    networks:
      - sepal
    restart: always

networks:
  sepal:
    external: true
    name: sepal
