- name: Configure Sepal instance
  hosts: all
  user: ec2-user
  become: yes
  gather_facts: true

  tasks:
    - name: Install amazon-efs-utils
      yum:
        name: 'amazon-efs-utils'

    - name: Create temp mount dir
      file:
        path: "/efs"
        state: "directory"

    - name: Temporarily Mount EFS Nfs4 For Setting Up Folders
      mount:
        name: "/efs"
        fstype: "efs"
        state: "mounted"
        src: "{{ lookup('env', 'AWS_EFS_ID') }}:/"
        opts: "defaults,_netdev"
        dump: 0
        passno: 0

    - name: Create sepal home dir on EFS
      file:
        path: "/efs/data/sepal/home"
        owner: "9999"
        group: "9999"
        mode: "u=rwx,g=rwxs"
        state: "directory"

    - name: Create sepal shiny dir on EFS
      file:
        path: "/efs/data/sepal/shiny"
        owner: "9999"
        group: "9999"
        mode: "u=rwx,g=rwxs"
        state: "directory"

    - name: Create sepal shared dir on EFS
      file:
        path: "/efs/data/sepal/shared"
        owner: "9999"
        group: "9999"
        mode: "u=rwx,g=rwxs"
        state: "directory"

    - name: Create sepal kernels dir on EFS
      file:
        path: "/efs/data/sepal/kernels"
        owner: "9999"
        group: "9999"
        mode: "u=rwx,g=rwxs"
        state: "directory"

    - name: Create sepal worker instance log dir on EFS
      file:
        path: "/efs/data/sepal/worker-instance-log"
        owner: "root"
        group: "root"
        mode: "u=rwx,g=rwxs"
        state: "directory"

    - name: Unmount EFS Nfs4
      mount:
          name: "/efs"
          fstype: "efs"
          state: "unmounted"
          src: "{{ lookup('env', 'AWS_EFS_ID') }}:/"

    - name: Delete temp mount dir
      file:
          path: "/efs"
          state: "absent"
