- name: Setup AWS
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
#    - name: Create letsencrypt AWS user
#      community.aws.iam:
#        iam_type: user
#        name: letsencrypt
#        state: present
#        access_key_state: create
#      register: letsencrypt_user

    - name: Create letsencrypt AWS user
      community.aws.iam_user:
        name: letsencrypt
        state: present
      register: letsencrypt_user

    - name: Create letsencrypt user policy
      community.aws.iam_policy:
        iam_type: user
        iam_name: letsencrypt
        policy_name: letsencrypt_policy
        policy_json: >
          {
              "Version": "2012-10-17",
              "Statement": [
                  {
                      "Effect": "Allow",
                      "Action": [
                          "route53:GetHostedZone",
                          "route53:ListHostedZones",
                          "route53:ListHostedZonesByName",
                          "route53:GetHostedZoneCount",
                          "route53:ChangeResourceRecordSets",
                          "route53:ListResourceRecordSets"
                      ],
                      "Resource": "*"
                  }
              ]
          }
        state: present

#    - name: Store letsencrypt keys
#      copy:
#        content: "letsencrypt_access_key_id: {{ letsencrypt_user['created_keys'][0]['access_key_id'] }}\nletsencrypt_secret_access_key: {{ letsencrypt_user['created_keys'][0]['secret_access_key'] }}\n"
#        dest: "{{ letsencrypt_aws_keys_file }}"
#      when: letsencrypt_user['created_keys']

    - name: Create Sepal-Storage security group
      ec2_group:
        name: "Sepal-Storage"
        description: The Sepal-Storage Security Group
        region: "{{ lookup('env', 'AWS_REGION') }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 168.202.0.0/16
            rule_desc: 'FAO'
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ local_ip_address }}/32"
            rule_desc: 'Deployer'
        rules_egress:
          - proto: all
            from_port: 0
            to_port: 65535
            cidr_ip: 0.0.0.0/0
      register: sepal_storage_group

    - name: Provision Sepal-Storage instance
      ec2:
        key_name: "{{ lookup('env', 'AWS_REGION') }}"
        group: "Sepal-Storage"
        instance_type: m5a.large
        image: "{{ lookup('env', 'AWS_AMI') }}"
        region: "{{ lookup('env', 'AWS_REGION') }}"
        zone: "{{ lookup('env', 'AWS_AVAILABILITY_ZONE') }}"
        wait: true
        instance_tags:
          Name: "Sepal-Storage - {{ lookup('env', 'DEPLOY_ENVIRONMENT') }}"
          Type: "SepalStorage"
          Environment: "{{ lookup('env', 'DEPLOY_ENVIRONMENT') }}"
        exact_count: 1
        count_tag:
          Type: "SepalStorage"
          Environment: "{{ lookup('env', 'DEPLOY_ENVIRONMENT') }}"
        volumes:
          - device_name: /dev/xvda
            delete_on_termination: false
            volume_type: gp2
            volume_size: 32
          - device_name: /dev/sdb
            delete_on_termination: false
            volume_type: gp2
            volume_size: 32
      register: started_ec2_sepal_storage

    - ec2_instance_info:
        region: "{{ lookup('env', 'AWS_REGION') }}"
        filters:
          "tag:Type": "SepalStorage"
          "tag:Environment": "{{ lookup('env', 'DEPLOY_ENVIRONMENT') }}"
      register: ec2_sepal_storage

    - set_fact:
        sepal_storage_ip: "{{ ec2_sepal_storage.instances[0].public_ip_address }}"

    - name: Create Sepal security group
      ec2_group:
        name: "Sepal"
        description: The Sepal Security Group
        region: "{{ lookup('env', 'AWS_REGION') }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 168.202.0.0/16
            rule_desc: 'FAO'
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
            rule_desc: 'HTTP'
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
            rule_desc: 'HTTPS'
          - proto: udp
            from_port: 514
            to_port: 514
            cidr_ip: 172.31.0.0/16
            rule_desc: 'syslog'
          - proto: tcp
            from_port: 0
            to_port: 65535
            cidr_ip: 172.31.0.0/16
            rule_desc: 'Subnet'
          - proto: tcp
            from_port: 5672
            to_port: 5672
            cidr_ip: "{{ sepal_storage_ip }}/32"
            rule_desc: 'Sepal-Storage'
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ local_ip_address }}/32"
            rule_desc: 'Deployer'
        rules_egress:
          - proto: all
            from_port: 0
            to_port: 65535
            cidr_ip: 0.0.0.0/0

    - name: Create EFS security group
      ec2_group:
        name: EFS
        description: The EFS Security Group
        region: "{{ lookup('env', 'AWS_REGION') }}"
        rules:
          - proto: tcp
            from_port: 2049
            to_port: 2049
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            from_port: 0
            to_port: 65535
            cidr_ip: 0.0.0.0/0

    - name: Provision Sepal instance
      ec2:
        key_name: "{{ lookup('env', 'AWS_REGION') }}"
        group: "Sepal"
        instance_type: "{{ lookup('env', 'AWS_INSTANCE_TYPE') }}"
        image: "{{ lookup('env', 'AWS_AMI') }}"
        region: "{{ lookup('env', 'AWS_REGION') }}"
        zone: "{{ lookup('env', 'AWS_AVAILABILITY_ZONE') }}"
        wait: true
        exact_count: 1
        count_tag:
          Type: Sepal
          Environment: "{{ lookup('env', 'DEPLOY_ENVIRONMENT') }}"
        instance_tags:
          Name: "Sepal - {{ lookup('env', 'DEPLOY_ENVIRONMENT') }}"
          Type: Sepal
          Environment: "{{ lookup('env', 'DEPLOY_ENVIRONMENT') }}"
        ebs_optimized: true
        volumes:
          - device_name: /dev/xvda
            delete_on_termination: false
            volume_type: gp2
            volume_size: 100
          - device_name: /dev/sdb
            delete_on_termination: false
            volume_type: gp2
            volume_size: 100
      register: started_ec2_sepal

    - name: Wait for SSH to be available on Sepal
      local_action: wait_for host="{{ item.public_ip }}"
                    port=22
                    state="started"
      with_items: "{{ started_ec2_sepal.instances }}"

    - name: Wait for SSH to be available on Sepal-Storage
      local_action: wait_for host="{{ item.public_ip }}"
                    port=22
                    state="started"
      with_items: "{{ started_ec2_sepal_storage.instances }}"
