- name: Configure Sandbox Image
  strategy: debug
  hosts: default
  user: ec2-user
  become: yes
  gather_facts: true

  tasks:
    - name: Create /data/sepal
      file:
        path: "/data/sepal"
        state: directory

    - name: Create /data/ldap
      file:
        path: "/data/sepal"
        state: directory

    - name: Create /data/ldap/certificates
      file:
        path: "/data/ldap/certificates"
        state: directory

    - name: Copy LDAP Certificate
      copy:
       src: "{{ CONFIG_HOME }}/certificates/ldap-ca.crt.pem"
       dest: "/data/ldap/certificates/ldap-ca.crt.pem"

    # EFS setup
    - name: Install nfs-utils
      yum:
        name: "nfs-utils"

    - name: Install amazon-efs-utils
      yum:
        name: 'amazon-efs-utils'

    - name: Create /data/sepal/home
      file:
        path: "/data/sepal/home"
        state: directory

    - name: Mount EFS to /data/sepal/home
      mount:
        name: "/data/sepal/home"
        fstype: "efs"
        state: "mounted"
        src: "{{ lookup('env', 'AWS_EFS_ID') }}:/data/sepal/home"
        opts: "defaults,_netdev"
        dump: 0
        passno: 0

    - name: Create /data/sepal/shiny
      file:
        path: "/data/sepal/shiny"
        state: directory

    - name: Mount EFS to /data/sepal/shiny
      mount:
        name: "/data/sepal/shiny"
        fstype: "efs"
        state: "mounted"
        src: "{{ lookup('env', 'AWS_EFS_ID') }}:/data/sepal/shiny"
        opts: "defaults,_netdev"
        dump: 0
        passno: 0

    - name: Create /data/sepal/shared
      file:
        path: "/data/sepal/shared"
        state: directory

    - name: Mount EFS to /data/sepal/shared
      mount:
        name: "/data/sepal/shared"
        fstype: "efs"
        state: "mounted"
        src: "{{ lookup('env', 'AWS_EFS_ID') }}:/data/sepal/shared"
        opts: "defaults,_netdev"
        dump: 0
        passno: 0

    - name: Create /data/sepal/kernels
      file:
        path: "/data/sepal/kernels"
        state: directory

    - name: Mount EFS to /data/sepal/kernels
      mount:
        name: "/data/sepal/kernels"
        fstype: "efs"
        state: "mounted"
        src: "{{ lookup('env', 'AWS_EFS_ID') }}:/data/sepal/kernels"
        opts: "defaults,_netdev"
        dump: 0
        passno: 0

    # GPU setup
    - name: Copy GPU drivers init script
      copy:
        src: "gpu/init-gpu-drivers.sh"
        dest: "/usr/local/bin/init-gpu-drivers.sh"

    - name: Copy GPU drivers init service
      copy:
        src: "gpu/init-gpu-drivers.service"
        dest: "/etc/systemd/system/init-gpu-drivers.service"

    - name: Install GPU drivers
      script: "gpu/install-gpu-drivers.sh"
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

    # Docker setup
    - name: Create filesystem on Docker volume
      filesystem:
        fstype: xfs
        dev: /dev/xvdf

    - name: Mount Docker volume
      mount:
        path: /var/lib/docker
        src: /dev/xvdf
        fstype: xfs
        state: mounted

    - name: Create docker-registry certificate dir
      file:
        path: "/etc/docker/certs.d/{{ lookup('env', 'DOCKER_REGISTRY_HOST') }}"
        state: directory

    - name: Copy docker-registry certificate
      copy:
        src: "{{ CONFIG_HOME }}/certificates/docker-registry.crt"
        dest: "/etc/docker/certs.d/{{ lookup('env', 'DOCKER_REGISTRY_HOST') }}/ca.crt"

    - name: Install docker
      command: "amazon-linux-extras install docker -y"

    - name: Create /etc/docker
      file:
        path: "/etc/docker"
        state: directory

    - name: Copy /etc/docker/daemon.json
      copy: src=docker/worker-daemon.json dest=/etc/docker/daemon.json

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker

    - name: Create /etc/systemd/system/docker.service.d
      file:
        path: "/etc/systemd/system/docker.service.d"
        state: directory
    - name: Copy /etc/systemd/system/docker.service.d/docker.conf
      copy: src=docker/docker.conf dest=/etc/systemd/system/docker.service.d/docker.conf

    - name: Enable docker
      systemd:
        name: docker
        state: started
        enabled: yes
        masked: no

    - name: Login to docker registry
      command: "docker login -p '{{ lookup('env', 'DOCKER_REGISTRY_PASSWORD') }}' -u '{{ lookup('env', 'DOCKER_REGISTRY_USERNAME') }}' {{ lookup('env', 'DOCKER_REGISTRY_HOST') }}"

    - name: Pull sandbox
      command: "docker pull {{ lookup('env', 'DOCKER_REGISTRY_HOST') }}/openforis/sandbox:{{ VERSION }}"

    - name: Pull task
      command: "docker pull {{ lookup('env', 'DOCKER_REGISTRY_HOST') }}/openforis/task:{{ VERSION }}"

    - name: Logout from docker registry
      command: "docker logout {{ lookup('env', 'DOCKER_REGISTRY_HOST') }}"
