- name: Configure Sandbox Image
  strategy: debug
  hosts: default
  user: ec2-user
  become: yes
  gather_facts: true

  vars_files:
    - "{{ secret_vars_file }}"

  tasks:
    - name: Copy GPU drivers init script
      copy:
        src: "gpu/init-gpu-drivers.sh"
        dest: "/usr/local/bin/init-gpu-drivers.sh"

    - name: Copy GPU drivers init service
      copy:
        src: "gpu/init-gpu-drivers.service"
        dest: "/etc/systemd/system/init-gpu-drivers.service"

    - name: Install GPU drivers
      script: "gpu/install-gpu-drivers.sh"
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"

    - name: Install nfs-utils
      yum:
        name: "nfs-utils"

    - name: Create /data/sepal
      file:
        path: "/data/sepal"
        state: directory

    - name: Create /data/ldap
      file:
        path: "/data/sepal"
        state: directory

    - name: Create /data/sepal/home
      file:
        path: "/data/sepal/home"
        state: directory

    - name: Create /data/sepal/shiny
      file:
        path: "/data/sepal/shiny"
        state: directory

    - name: Create /data/sepal/shared
      file:
        path: "/data/sepal/shared"
        state: directory

    - name: Create /data/sepal/kernels
      file:
        path: "/data/sepal/kernels"
        state: directory

    - name: Create /data/ldap/certificates
      file:
        path: "/data/sepal/certificates"
        state: directory

    - name: Install amazon-efs-utils
      yum:
        name: 'amazon-efs-utils'

    - name: Mount EFS Sepal Home Dir
      mount:
        name: "/data/sepal/home"
        fstype: "efs"
        state: "mounted"
        src: "{{ efs_id }}:/data/sepal/home"
        opts: "defaults,_netdev"
        dump: 0
        passno: 0

    - name: Mount EFS Sepal Shiny Dir
      mount:
        name: "/data/sepal/shiny"
        fstype: "efs"
        state: "mounted"
        src: "{{ efs_id }}:/data/sepal/shiny"
        opts: "defaults,_netdev"
        dump: 0
        passno: 0

    - name: Mount EFS Sepal Shared Dir
      mount:
        name: "/data/sepal/shared"
        fstype: "efs"
        state: "mounted"
        src: "{{ efs_id }}:/data/sepal/shared"
        opts: "defaults,_netdev"
        dump: 0
        passno: 0

    - name: Mount EFS Sepal Kernels Dir
      mount:
        name: "/data/sepal/kernels"
        fstype: "efs"
        state: "mounted"
        src: "{{ efs_id }}:/data/sepal/kernels"
        opts: "defaults,_netdev"
        dump: 0
        passno: 0

    - name: Copy LDAP Certificate
      copy:
       src: "{{ config_home }}/certificates/ldap-ca.crt.pem"
       dest: "/data/ldap/certificates/ldap-ca.crt.pem"

    - name: Create filesystem on Docker volume
      filesystem:
        fstype: xfs
        dev: /dev/xvdf

    - name: Mount Docker volume
      mount:
        path: /var/lib/docker
        src: /dev/xvdf
        fstype: xfs
        state: mounted

    - name: Create docker-registry certificate dir
      file:
        path: "/etc/docker/certs.d/{{ docker_repository_host }}"
        state: directory

    - name: Copy docker-registry certificate
      copy:
        src: "{{ config_home }}/certificates/docker-registry.crt"
        dest: "/etc/docker/certs.d/{{ docker_repository_host }}/ca.crt"

    - name: Install docker
      command: "amazon-linux-extras install docker -y"

    - name: Create /etc/docker
      file:
        path: "/etc/docker"
        state: directory

    - name: Copy /etc/docker/daemon.json
      copy: src=docker/worker-daemon.json dest=/etc/docker/daemon.json

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker

    - name: Create /etc/systemd/system/docker.service.d
      file:
        path: "/etc/systemd/system/docker.service.d"
        state: directory
    - name: Copy /etc/systemd/system/docker.service.d/docker.conf
      copy: src=docker/docker.conf dest=/etc/systemd/system/docker.service.d/docker.conf

    - name: Enable docker
      systemd:
        name: docker
        state: started
        enabled: yes
        masked: no

    - name: Login to docker registry
      command: "docker login -p '{{ docker_password }}' -u '{{ docker_username }}' {{ docker_repository_host }}"

    - name: Pull sandbox
      command: "docker pull {{ docker_repository_host }}/openforis/sandbox:{{ version }}"

    - name: Pull task
      command: "docker pull {{ docker_repository_host }}/openforis/task:{{ version }}"

    - name: Logout from docker registry
      command: "docker logout {{ docker_repository_host }}"
