services:
  email-redis:
    extends:
      file: ../docker-compose.logger.override.yml
      service: logger
      
  email:
    extends:
      file: ../docker-compose.logger.override.yml
      service: logger
    volumes:  # To allow dynamic reloading in dev
      - ${SEPAL_PROJECT_DIR}/lib/js/shared:/usr/local/src/sepal/lib/js/shared
      - ${SEPAL_PROJECT_DIR}/modules/email:/usr/local/src/sepal/modules/email
