version: "3.9"

services:
  app-manager:
    build:
      context: ../..
      dockerfile: ./modules/app-manager/Dockerfile
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/app-manager:${SEPAL_VERSION:-latest}"
    container_name: app-manager
    init: true
    volumes:
      - "${SEPAL_DATA_DIR}/sepal/shiny:/shiny"
      - "${SEPAL_DATA_DIR}/sepal/kernels:/usr/local/share/jupyter/kernels"
      - "${SEPAL_DATA_DIR}/app-manager/apps.json:/var/sepal/app-manager/apps.json"
      - "${SEPAL_DATA_DIR}/sepal/shared/apps:/var/sepal/app-manager/apps"
      - "${SEPAL_DATA_DIR}/app-manager/images:/var/sepal/app-manager/images"
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
    networks:
      - sepal

networks:
  sepal:
    external: true
    name: sepal
