version: "3.9"

services:
  app-manager:
    build:
      context: ../..
      dockerfile: ./modules/app-manager/Dockerfile
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/app-manager:${SEPAL_VERSION:-latest}"
    container_name: app-manager
    init: true
    volumes:
      - "${SEPAL_DATA_DIR}/sepal/shiny:/shiny"
      - "${SEPAL_DATA_DIR}/sepal/jupyter:/usr/local/share/jupyter"
      - "${SEPAL_DATA_DIR}/app-manager/apps.json:/var/lib/sepal/app-manager/apps.json"
      - "${SEPAL_DATA_DIR}/sepal/shared/apps:/var/lib/sepal/app-manager/apps"
      - "${SEPAL_DATA_DIR}/app-manager/images:/var/lib/sepal/app-manager/images"
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
    networks:
      - sepal
    restart: always
    ulimits:
      core: 0

networks:
  sepal:
    external: true
    name: sepal
