version: "3.9"

services:
  java:
    build:
      context: ../..
      dockerfile: ./modules/java/Dockerfile
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
    image: "openforis/java:latest"
