version: "3.9"

services:
  java:
    build:
      context: ../..
      dockerfile: ./modules/java/Dockerfile
    image: "${SEPAL_DOCKER_REPOSITORY:-localhost}/openforis/java:${SEPAL_VERSION:-latest}"
