version: "3"
services:
    sepal-dev-env:
        build: .
        image: $IMAGE_NAME
        container_name: $CONTAINER_NAME
        hostname: sepal-dev-env
        ports:
            - "3000:3000"
            - "8001:8001"
        command: bash
        tty: true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - $PROJECT_DIR:/usr/local/lib/sepal:delegated
            - $DATA_DIR:/var/sepal:Z,delegated
            - $CONFIG_DIR:/etc/sepal/conf.d:delegated
    rabbitmq:
        image: rabbitmq:3-management
        container_name: sepal-rabbitmq
        hostname: rabbitmq
        ports:
            - "15671-15672:15671-15672"
    user-storage-redis:
        image: redis:6
        container_name: sepal-user-storage-redis
        hostname: user-storage-redis
        volumes:
            - $DATA_DIR/user-storage-redis:/data:delegated
    email-redis:
        image: redis:6
        container_name: sepal-email-redis
        hostname: email-redis
        volumes:
            - $DATA_DIR/email-redis:/data:delegated
    email:
        build: ../modules/email/docker
        image: sepal-email
        container_name: sepal-email
        hostname: email
        environment:
            RABBITMQ_HOST: "sepal-rabbitmq"
            RABBITMQ_PORT: "15672"
            # RABBITMQ_URI: "amqp://rabbitmq"
            # REDIS_URI: "redis://email-redis"
            SMTP_HOST: "smtp.ethereal.email"
            SMTP_PORT: "587"
            SMTP_SECURE: "false"
            SMTP_USER: "derrick.goodwin@ethereal.email"
            SMTP_PASSWORD: "DFVFth6hNJ5Y7c1mjt"
            SMTP_FROM_DOMAIN: "dev.sepal.io"
            SEPAL_HOST_SEPAL_ENV: "localhost:3000"
            # SEPAL_ADMIN_USERNAME: "sepalAdmin"
            # SEPAL_ADMIN_PASSWORD_SEPAL_ENV: "the admin password"
