version: "3"
services:
  sepal-dev-env:
    build: .
    image: $IMAGE_NAME
    container_name: $CONTAINER_NAME
    hostname: sepal-dev-env
    ports:
      - "3000:3000"
      - "8001:8001"
    command: bash
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PROJECT_DIR:/usr/local/lib/sepal:delegated
      - $DATA_DIR:/var/sepal:Z,delegated
      - $CONFIG_DIR:/etc/sepal/conf.d:delegated
  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      ports:
        - "15671-15672:15671-15672"
      hostname: rabbitmq
  gateway-redis:
      image: redis:6
      container_name: gateway-redis
      hostname: gateway-redis
      volumes:
        - $DATA_DIR/gateway-redis:/data:delegated
  user-storage-redis:
      image: redis:6
      container_name: user-storage-redis
      hostname: user-storage-redis
      volumes:
        - $DATA_DIR/user-storage-redis:/data:delegated
  email-redis:
      image: redis:6
      container_name: email-redis
      hostname: email-redis
      volumes:
        - $DATA_DIR/email-redis:/data:delegated
