version: "3.9"

services:
  sepal-dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: sepal-dev
    tty: true
    stdin_open: true
    container_name: sepal-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./src:/dev-env/src
      - ..:/usr/local/src/sepal
      - ${SEPAL_ENV:-~/.sepal}:/usr/local/lib/sepal-env
    