version: "3.9"

services:
  user-storage-redis:
    image: "redis:6"
    container_name: user-storage-redis
    volumes:
      - "${SEPAL_DATA_DIR}/user-storage-redis:/data"
    networks:
      - sepal
    restart: always

  user-storage:
    build:
      context: ../..
      dockerfile: ./modules/user-storage/Dockerfile
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/user-storage:${SEPAL_VERSION:-latest}"
    container_name: user-storage
    init: true
    volumes:
      - "${SEPAL_DATA_DIR}/sepal/home:/sepalUsers"
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
      RABBITMQ_HOST: "${RABBITMQ_HOST:-rabbitmq}"
      RABBITMQ_PORT: "5672"
      MIN_DELAY_SECONDS: "300"
      MAX_DELAY_SECONDS: "86400"
      DELAY_INCREASE_FACTOR: "2"
      CONCURRENCY: "5"
      MAX_RETRIES: "10"
      INITIAL_RETRY_DELAY_SECONDS: "30"
    networks:
      - sepal
    restart: always
    ulimits:
      core: 0

networks:
  sepal:
    external: true
    name: sepal
