version: "3.9"

services:
  user-storage:
    volumes:  # To allow dynamic reloading in dev
      - ${SEPAL_PROJECT_DIR}/dev-env/nodemon:/usr/local/src/sepal/dev-env/nodemon
      - ${SEPAL_PROJECT_DIR}/lib/js/shared:/usr/local/src/sepal/lib/js/shared
      - ${SEPAL_PROJECT_DIR}/modules/user-storage:/usr/local/src/sepal/modules/user-storage
