services:
  mysql-backup:
    extends:
      file: ../docker-compose.logger.yml
      service: logger
    build:
      context: ../..
      dockerfile: ./modules/mysql-backup/Dockerfile
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/mysql-backup:${SEPAL_VERSION:-latest}"
    container_name: mysql-backup
    volumes:
      - "${SEPAL_BACKUP_DIR}/mysql:/backup"
      - "${SEPAL_DATA_DIR}/mysql-backup:/module"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      BACKUP_CRON_EXP: '0 0 * * *'
      RESTORE_BACKUP: "${RESTORE_BACKUP}"
    networks:
      - sepal
    restart: always

networks:
  sepal:
    external: true
