services:
  ldap:
    extends:
      file: ../docker-compose.logger.yml
      service: logger
    build:
      context: ../..
      dockerfile: ./modules/ldap/Dockerfile
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/ldap:${SEPAL_VERSION:-latest}"
    container_name: ldap
    volumes:
      - "${SEPAL_DATA_DIR}/ldap:/data"
      # Parent image volumes
      - "${SEPAL_DATA_DIR}/ldap/database:/var/lib/ldap"
      - "${SEPAL_DATA_DIR}/ldap/config:/etc/ldap/slapd.d"
      - "${SEPAL_DATA_DIR}/ldap/certificates:/container/service/slapd/assets/certs"
    environment:
      LDAP_ORGANISATION: "SEPAL"
      LDAP_DOMAIN: "sepal.org"
      LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWORD}"
      LDAP_TLS_CRT_FILENAME: ldap-crt.pem
      LDAP_TLS_KEY_FILENAME: ldap-key.pem
      LDAP_TLS_CA_CRT_FILENAME: ldap-ca.crt.pem
      LDAP_TLS_CIPHER_SUITE: SECURE256:-VERS-SSL3.0
      LDAP_TLS_VERIFY_CLIENT: never
    networks:
      - sepal
    healthcheck:
      test: bash -c "test -f /data/content_added && [ ! -f '/container/environment/99-default/default.startup.yaml' ]"
      timeout: 60s
      interval: 1s
      retries: 60
    restart: always

networks:
  sepal:
    external: true
